# Configuration Dependabot (backup pour Renovate)
version: 2
updates:
  # Surveillance des dépendances npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
    open-pull-requests-limit: 5
    reviewers:
      - "casskai-team"
    labels:
      - "dependencies"
      - "dependabot"
    commit-message:
      prefix: "chore(deps)"
      include: "scope"
    ignore:
      # Laisser Renovate gérer ces dépendances
      - dependency-name: "@types/*"
      - dependency-name: "eslint*"
      - dependency-name: "prettier"
      
  # Surveillance des Actions GitHub
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "casskai-team"
    labels:
      - "ci/cd"
      - "dependabot"
    commit-message:
      prefix: "chore(ci)"
      
  # Surveillance des images Docker
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "06:00"
    open-pull-requests-limit: 2
    reviewers:
      - "casskai-team"
    labels:
      - "docker"
      - "dependabot"
    commit-message:
      prefix: "chore(docker)"