import React, { useState } from 'react';
import { useParams, useNavigate } from 'react-router-dom';
import { useTranslation } from 'react-i18next';
import { useToast } from '@/components/ui/use-toast';
import { motion } from 'framer-motion';
import {
  ArrowLeft,
  Clock,
  User,
  Calendar,
  BookOpen,
  CheckCircle,
  ArrowRight,
  MessageCircle,
  ThumbsUp,
  ThumbsDown,
  Share2,
  Copy,
  Star
} from 'lucide-react';
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card';
import { Badge } from '@/components/ui/badge';
import { Button } from '@/components/ui/button';
import { PageContainer } from '@/components/ui/PageContainer';
import { PublicNavigation } from '@/components/navigation/PublicNavigation';
import { categoriesData } from './DocumentationCategoryPage';
import { WhatsAppChat } from '@/components/chat/WhatsAppChat';
import { logger } from '@/utils/logger';

// Base de données simplifiée des articles
const articlesDatabase = {
  'creer-votre-premier-compte': {
    id: 'creer-votre-premier-compte',
    title: 'Créer votre premier compte',
    category: 'Premiers pas',
    description: 'Guide complet pour créer votre compte CassKai et commencer à utiliser la plateforme',
    readTime: '5 min',
    difficulty: 'Débutant',
    lastUpdated: '2025-01-15',
    author: 'Équipe CassKai',
    rating: 4.8,
    views: 1205,
    content: [
      '# Créer votre premier compte CassKai',
      '',
      'Bienvenue dans CassKai ! Ce guide vous accompagne étape par étape pour créer votre compte et configurer votre espace de travail.',
      '',
      '## Prérequis',
      '',
      '- Une adresse email valide',
      '- Informations de votre entreprise (SIREN, adresse, etc.)',
      '- 5 minutes de votre temps',
      '',
      '## Étape 1 : Inscription',
      '',
      '1. Rendez-vous sur casskai.app',
      '2. Cliquez sur "Commencer l\'essai gratuit"',
      '3. Saisissez vos informations personnelles',
      '',
      '## Étape 2 : Configuration de l\'entreprise',
      '',
      'Lors de votre première connexion, vous devrez renseigner :',
      '',
      '**Informations obligatoires**',
      '- Dénomination sociale : Le nom officiel de votre entreprise',
      '- SIREN : Votre numéro d\'identification (9 chiffres)',
      '- Adresse du siège : L\'adresse officielle de votre entreprise',
      '- Secteur d\'activité : Choisissez dans la liste proposée',
      '',
      '## Étape 3 : Choix du plan comptable',
      '',
      'CassKai propose plusieurs référentiels :',
      '',
      '- Plan comptable français (PCG 2014)',
      '- Plan comptable SYSCOHADA (pour l\'Afrique de l\'Ouest et Centrale)',
      '- Plan comptable personnalisé',
      '',
      '💡 **Conseil** : Vous pourrez modifier ce choix ultérieurement dans les paramètres.',
      '',
      '## Prochaines étapes',
      '',
      'Maintenant que votre compte est configuré :',
      '',
      '1. Créez votre première facture',
      '2. Configurez vos comptes bancaires',
      '3. Invitez vos collaborateurs',
      '',
      '## Besoin d\'aide ?',
      '',
      '- 💬 Chat en direct : Disponible 24/7',
      '- 📧 Email : support@casskai.app',
      '- 📞 Téléphone : +33 6 88 89 33 72'
    ],
    relatedArticles: [
      'configuration-de-entreprise',
      'tour-d-horizon-de-interface',
      'invitation-des-collaborateurs'
    ]
  },
  
  'creer-une-facture': {
    id: 'creer-une-facture',
    title: 'Comment créer votre première facture',
    category: 'Facturation',
    description: 'Guide complet pour créer et envoyer votre première facture avec CassKai',
    readTime: '5 min',
    difficulty: 'Débutant',
    lastUpdated: '2025-01-10',
    author: 'Équipe CassKai',
    rating: 4.9,
    views: 2540,
    content: [
      '# Comment créer votre première facture',
      '',
      'Créer une facture professionnelle n\'a jamais été aussi simple avec CassKai. Suivez ce guide pas à pas.',
      '',
      '## Accéder au module Facturation',
      '',
      '1. Depuis votre tableau de bord, cliquez sur **📄 Facturation**',
      '2. Sélectionnez **"Nouvelle facture"**',
      '3. Choisissez le type de facture :',
      '   - **Facture simple** : Pour une vente ponctuelle',
      '   - **Facture récurrente** : Pour un abonnement',
      '   - **Facture d\'acompte** : Pour un paiement partiel',
      '',
      '## Sélectionner le client',
      '',
      '### Client existant',
      '1. Commencez à taper le nom dans le champ "Client"',
      '2. Sélectionnez le client dans la liste déroulante',
      '3. Ses informations se complètent automatiquement',
      '',
      '### Nouveau client',
      '1. Cliquez sur **"+ Nouveau client"**',
      '2. Remplissez les informations obligatoires :',
      '   - Dénomination ou nom/prénom',
      '   - Adresse complète',
      '   - SIRET (si professionnel)',
      '',
      '## Ajouter des lignes de facture',
      '',
      'Pour chaque produit ou service :',
      '',
      '1. **Description** : Décrivez clairement la prestation',
      '2. **Quantité** : Nombre d\'unités',
      '3. **Prix unitaire HT** : Prix avant taxes',
      '4. **TVA** : Sélectionnez le taux approprié',
      '',
      '💡 **Astuce** : Utilisez les modèles de lignes pour gagner du temps.',
      '',
      '## Envoi de la facture',
      '',
      '### Par email (recommandé)',
      '1. L\'email du client est pré-rempli',
      '2. Personnalisez l\'objet et le message',
      '3. La facture PDF est automatiquement jointe',
      '4. Cliquez sur **"Envoyer"**',
      '',
      '## Suivi après envoi',
      '',
      '### Statuts de facture',
      '- 📝 **Brouillon** : En cours de création',
      '- 📤 **Envoyée** : Transmise au client',
      '- 💰 **Payée** : Montant encaissé',
      '- ⏰ **Échue** : Dépassement du délai',
      '',
      '## Articles complémentaires',
      '',
      '- Personnaliser les modèles de facture',
      '- Gérer les factures récurrentes',
      '- Configurer les relances automatiques'
    ],
    relatedArticles: [
      'personnaliser-les-modeles',
      'suivi-des-paiements',
      'factures-recurrentes'
    ]
  },

  'configuration-plan-comptable-syscohada': {
    id: 'configuration-plan-comptable-syscohada',
    title: 'Configuration des plans comptables',
    category: 'Comptabilité',
    description: 'Paramétrer votre plan comptable selon vos normes locales',
    readTime: '8 min',
    difficulty: 'Intermédiaire',
    lastUpdated: '2025-01-12',
    author: 'Expert Comptable OHADA',
    rating: 4.7,
    views: 890,
    content: [
      '# Configuration du plan comptable SYSCOHADA',
      '',
      'Le Système Comptable OHADA (SYSCOHADA) révisé est obligatoire pour les entreprises des 17 pays membres de l\'OHADA.',
      '',
      '## Qu\'est-ce que le SYSCOHADA ?',
      '',
      'Le SYSCOHADA est le référentiel comptable unifié pour les pays OHADA :',
      '',
      '### Pays membres OHADA',
      '🇧🇯 Bénin • 🇧🇫 Burkina Faso • 🇨🇲 Cameroun • 🇹🇩 Tchad • 🇨🇮 Côte d\'Ivoire • 🇬🇦 Gabon',
      '🇬🇭 Ghana • 🇬🇳 Guinée • 🇬🇼 Guinée-Bissau • 🇲🇱 Mali • 🇳🇪 Niger • 🇸🇳 Sénégal • 🇹🇬 Togo',
      '',
      '## Activation du plan SYSCOHADA',
      '',
      '### Nouvelle entreprise',
      '1. Lors de l\'onboarding, sélectionnez **"Plan comptable SYSCOHADA"**',
      '2. Choisissez votre pays pour les spécificités locales',
      '3. La configuration se fait automatiquement',
      '',
      '### Entreprise existante',
      '1. Allez dans **Paramètres > Comptabilité**',
      '2. Section **"Plan comptable"**',
      '3. Cliquez **"Changer de référentiel"**',
      '⚠️ **Attention** : Cette action nécessite une validation comptable',
      '',
      '## Structure du plan SYSCOHADA révisé',
      '',
      '### Classes principales',
      '',
      '#### Classe 1 - Comptes de ressources durables',
      '- **10** Capital et réserves',
      '- **16** Emprunts et dettes assimilées',
      '- **19** Provisions financières pour risques et charges',
      '',
      '#### Classe 2 - Comptes d\'actif immobilisé',
      '- **21** Immobilisations corporelles',
      '- **24** Matériels',
      '- **28** Amortissements des immobilisations',
      '',
      '#### Classe 4 - Comptes de tiers',
      '- **40** Fournisseurs et comptes rattachés',
      '- **41** Clients et comptes rattachés',
      '- **44** État et collectivités publiques',
      '',
      '#### Classe 6 - Comptes de charges',
      '- **60** Achats et variations de stocks',
      '- **62** Services extérieurs',
      '- **64** Charges de personnel',
      '',
      '#### Classe 7 - Comptes de produits',
      '- **70** Ventes',
      '- **75** Autres produits',
      '- **76** Produits financiers',
      '',
      '## Configuration dans CassKai',
      '',
      '### Étape 1 : Sélection du pays',
      'Choisissez votre pays pour adapter :',
      '- Les taux de TVA locaux',
      '- Les comptes d\'impôts spécifiques',
      '- Les obligations déclaratives',
      '- La devise de référence',
      '',
      '### Étape 2 : Paramétrage des comptes',
      'CassKai génère automatiquement :',
      '- Structure complète des classes 1 à 8',
      '- Comptes de TVA selon la législation locale',
      '- Journaux obligatoires (achats, ventes, banque)',
      '',
      '## États financiers SYSCOHADA',
      '',
      'CassKai génère automatiquement :',
      '',
      '#### États primaires',
      '- **Bilan** (modèle normal et simplifié)',
      '- **Compte de résultat** (nature et fonction)',
      '- **Tableau des flux de trésorerie** (TFT)',
      '',
      '## Formation et support',
      '',
      '### Ressources disponibles',
      '- 📚 Guide complet SYSCOHADA (200 pages)',
      '- 🎥 Vidéos de formation (15h de contenu)',
      '- 📞 Support téléphonique spécialisé OHADA'
    ],
    relatedArticles: [
      'ecritures-automatiques',
      'rapports-financiers',
      'export-fec'
    ]
  },

  'invitation-et-gestion-des-utilisateurs': {
    id: 'invitation-et-gestion-des-utilisateurs',
    title: 'Invitation et gestion des utilisateurs',
    category: 'Gestion d\'équipe',
    description: 'Ajouter des collaborateurs et définir leurs permissions',
    readTime: '6 min',
    difficulty: 'Débutant',
    lastUpdated: '2025-01-08',
    author: 'Équipe CassKai',
    rating: 4.6,
    views: 1450,
    content: [
      '# Invitation et gestion des utilisateurs',
      '',
      'Collaborer efficacement avec votre équipe grâce au système de gestion des utilisateurs de CassKai.',
      '',
      '## Types d\'utilisateurs',
      '',
      '### Administrateur',
      '**Accès complet** à toutes les fonctionnalités :',
      '- ✅ Gestion des utilisateurs et permissions',
      '- ✅ Configuration générale de l\'entreprise',
      '- ✅ Accès à tous les modules (compta, facturation, RH...)',
      '- ✅ Consultation des logs et statistiques',
      '',
      '### Comptable',
      '**Accès aux modules financiers** :',
      '- ✅ Comptabilité générale et analytique',
      '- ✅ Facturation et gestion commerciale',
      '- ✅ Banques et trésorerie',
      '- ✅ Déclarations fiscales',
      '- ❌ Gestion RH (sauf si autorisé)',
      '',
      '### Utilisateur Standard',
      '**Accès limité selon attribution** :',
      '- ✅ Consultation des données autorisées',
      '- ✅ Saisie dans les modules attribués',
      '- ✅ Édition de rapports spécifiques',
      '- ❌ Modification des paramètres',
      '',
      '## Inviter un nouvel utilisateur',
      '',
      '### Processus d\'invitation',
      '',
      '1. **Accéder à la gestion des utilisateurs**',
      '   - Allez dans **Paramètres > Utilisateurs**',
      '   - Cliquez sur **"+ Inviter un utilisateur"**',
      '',
      '2. **Renseigner les informations**',
      '   - Email : john.doe@entreprise.com',
      '   - Prénom : John',
      '   - Nom : Doe',
      '   - Poste : Comptable junior',
      '',
      '3. **Définir le niveau d\'accès**',
      '   - Sélectionnez le **rôle principal**',
      '   - Cochez les **modules autorisés**',
      '   - Configurez les **permissions spécifiques**',
      '',
      '4. **Envoyer l\'invitation**',
      '   - L\'utilisateur reçoit un email automatique',
      '   - Le lien d\'activation expire en 7 jours',
      '',
      '## Gestion des permissions avancées',
      '',
      '### Permissions par module',
      '',
      '#### Module Comptabilité',
      '- **Consultation** : Voir les écritures, bilans, comptes',
      '- **Saisie** : Créer des écritures, lettrage',
      '- **Validation** : Valider les écritures, clôtures',
      '',
      '#### Module Facturation',
      '- **Consultation** : Voir factures et devis',
      '- **Création** : Créer factures, avoir, devis',
      '- **Envoi** : Transmettre aux clients',
      '',
      '## Sécurité et authentification',
      '',
      '### Authentification à deux facteurs (2FA)',
      '**Obligatoire pour :**',
      '- Administrateurs',
      '- Comptables avec droit de validation',
      '- Accès aux données sensibles',
      '',
      '**Configuration :**',
      '1. SMS sur téléphone portable',
      '2. Application authenticator (Google, Microsoft)',
      '3. Codes de récupération d\'urgence',
      '',
      '### Politique de mots de passe',
      '**Critères obligatoires :**',
      '- Minimum 8 caractères',
      '- 1 majuscule, 1 minuscule, 1 chiffre',
      '- 1 caractère spécial',
      '- Renouvellement tous les 6 mois',
      '',
      '## Besoin d\'aide ?',
      '',
      'La gestion des utilisateurs est cruciale pour la sécurité. N\'accordez que les permissions nécessaires !'
    ],
    relatedArticles: [
      'ajouter-des-utilisateurs',
      'definir-les-roles',
      'securite-des-acces'
    ]
  },

  'connexion-bancaire-automatique': {
    id: 'connexion-bancaire-automatique',
    title: 'Connexion bancaire automatique',
    category: 'Intégrations',
    description: 'Synchroniser vos comptes bancaires pour un rapprochement automatique',
    readTime: '10 min',
    difficulty: 'Intermédiaire',
    lastUpdated: '2025-01-05',
    author: 'Expert Technique',
    rating: 4.5,
    views: 756,
    content: [
      '# Connexion bancaire automatique',
      '',
      'Automatisez votre comptabilité en synchronisant directement vos comptes bancaires avec CassKai.',
      '',
      '## Pourquoi connecter vos banques ?',
      '',
      '### Avantages de l\'automatisation',
      '- ⚡ **Gain de temps** : Fini la saisie manuelle des écritures',
      '- 🎯 **Précision** : Élimination des erreurs de frappe',
      '- 📊 **Vision temps réel** : Trésorerie actualisée en permanence',
      '- 🔍 **Rapprochement automatique** : Lettrage intelligent des écritures',
      '',
      '### Cas d\'usage pratiques',
      '- Suivi quotidien de trésorerie',
      '- Rapprochement bancaire automatisé',
      '- Détection des impayés clients',
      '- Analyse des charges récurrentes',
      '',
      '## Banques compatibles',
      '',
      '### France 🇫🇷',
      '**Banques universelles :**',
      '- BNP Paribas (particuliers & entreprises)',
      '- Crédit Agricole (toutes caisses régionales)',
      '- Société Générale (particuliers & pro)',
      '- LCL (Le Crédit Lyonnais)',
      '- Crédit Mutuel (fédérations)',
      '',
      '**Banques en ligne :**',
      '- Boursorama Banque',
      '- Fortuneo',
      '- ING Direct',
      '- Hello Bank! (BNP Paribas)',
      '',
      '### Afrique 🌍',
      '**Sénégal :**',
      '- CBAO Groupe Attijariwafa Bank',
      '- Banque Atlantique',
      '- UBA Sénégal',
      '- Ecobank Sénégal',
      '',
      '**Côte d\'Ivoire :**',
      '- Société Générale Côte d\'Ivoire',
      '- BNP Paribas BICI',
      '- Ecobank Côte d\'Ivoire',
      '- UBA Côte d\'Ivoire',
      '',
      '## Processus de connexion',
      '',
      '### Étape 1 : Préparation',
      '**Documents nécessaires :**',
      '- RIB de chaque compte à connecter',
      '- Identifiants de banque en ligne',
      '- Numéro de téléphone (pour validation SMS)',
      '',
      '**Vérifications préalables :**',
      '- ✅ Banque en ligne activée',
      '- ✅ Accès fonctionnel aux comptes',
      '- ✅ Dernière connexion récente (< 30 jours)',
      '',
      '### Étape 2 : Configuration dans CassKai',
      '1. **Accéder au module Banques**',
      '   - Menu **Banques > Comptes bancaires**',
      '   - Cliquez **"+ Ajouter un compte"**',
      '',
      '2. **Sélectionner votre établissement**',
      '   - Tapez le nom de votre banque',
      '   - Sélectionnez dans la liste',
      '   - Vérifiez le logo affiché',
      '',
      '3. **Renseigner vos identifiants**',
      '   - Numéro client : 12345678',
      '   - Code secret : (votre mot de passe)',
      '   - Code d\'accès : 123456 (si applicable)',
      '',
      '4. **Validation par la banque**',
      '   - SMS de confirmation reçu',
      '   - Code de validation saisi',
      '   - Autorisation accordée',
      '',
      '### Étape 3 : Sélection des comptes',
      '**Types de comptes détectés :**',
      '- 💳 Comptes courants professionnels',
      '- 💰 Comptes d\'épargne entreprise',
      '- 📱 Comptes livrets',
      '- 🏦 Comptes multi-devises',
      '',
      '## Catégorisation automatique',
      '',
      '### Intelligence artificielle intégrée',
      'CassKai analyse automatiquement :',
      '- **Libellé de l\'opération** (mots-clés)',
      '- **Montant et fréquence** (récurrence)',
      '- **Tiers identifié** (base clients/fournisseurs)',
      '- **Historique des catégories** (apprentissage)',
      '',
      '### Exemples de règles automatiques',
      '- "VIREMENT DE DUPONT SA" → Client DUPONT',
      '- "PRLV SEPA EDF" → Électricité',
      '- "CB CARREFOUR MARKET" → Achats bureautique',
      '- "FRAIS TENUE COMPTE" → Frais bancaires',
      '',
      '## Sécurité et confidentialité',
      '',
      '### Protection des données bancaires',
      '- 🔒 **Chiffrement AES-256** : Données et communications',
      '- 🏦 **Agrégateur certifié** : Partenaire agréé ACPR/BCE',
      '- 🔐 **Authentification forte** : 2FA obligatoire',
      '- 🚫 **Zero-storage** : Pas de stockage des identifiants',
      '',
      '### Conformité réglementaire',
      '**DSP2 (Directive européenne) :**',
      '- ✅ Consentement explicite du client',
      '- ✅ Renouvellement tous les 90 jours',
      '- ✅ Audit trail complet',
      '- ✅ Droit de révocation immédiate',
      '',
      '## Tarification des connexions',
      '',
      '### Modèle de facturation',
      '- **Comptes inclus** : 3 comptes par défaut',
      '- **Comptes supplémentaires** : 5€/mois par compte',
      '- **Historique étendu** : +2€/mois (> 12 mois)',
      '- **Multi-établissements** : Gratuit',
      '',
      'La synchronisation bancaire transforme votre comptabilité. Testez dès maintenant !'
    ]
  },
  'introduction-api': {
    id: 'introduction-api',
    title: 'Introduction à l\'API CassKai',
    category: 'API et webhooks',
    description: 'Découvrez les bases de l\'API REST de CassKai et comment l\'utiliser',
    readTime: '8 min',
    difficulty: 'Intermédiaire',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.6,
    views: 856,
    content: [
      '# Introduction à l\'API CassKai',
      '',
      'L\'API CassKai vous permet d\'intégrer facilement vos données comptables et de facturation avec vos applications tierces.',
      '',
      '## Vue d\'ensemble',
      '',
      'L\'API CassKai est une API REST moderne qui respecte les standards de l\'industrie :',
      '',
      '- **Architecture REST** : Endpoints logiques et prévisibles',
      '- **Format JSON** : Toutes les données en JSON',
      '- **HTTPS uniquement** : Sécurité SSL/TLS obligatoire',
      '- **Authentification Bearer** : Tokens JWT sécurisés',
      '- **Rate limiting** : Protection contre les abus',
      '',
      '## URL de base',
      '',
      '```',
      'https://api.casskai.app/v1/',
      '```',
      '',
      '## Authentification',
      '',
      'Toutes les requêtes doivent inclure un token d\'authentification dans l\'en-tête :',
      '',
      '```http',
      'Authorization: Bearer YOUR_API_TOKEN',
      'Content-Type: application/json',
      '```',
      '',
      '## Structure des réponses',
      '',
      '### Réponse de succès',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {...},',
      '  "pagination": {',
      '    "page": 1,',
      '    "limit": 20,',
      '    "total": 150',
      '  }',
      '}',
      '```',
      '',
      '### Réponse d\'erreur',
      '```json',
      '{',
      '  "success": false,',
      '  "error": {',
      '    "code": "VALIDATION_ERROR",',
      '    "message": "Champ requis manquant",',
      '    "details": [...]',
      '  }',
      '}',
      '```',
      '',
      '## Codes de statut HTTP',
      '',
      '- **200** : Succès',
      '- **201** : Ressource créée',
      '- **400** : Erreur de validation',
      '- **401** : Non authentifié',
      '- **403** : Accès refusé',
      '- **404** : Ressource non trouvée',
      '- **429** : Trop de requêtes',
      '- **500** : Erreur serveur',
      '',
      '## Pagination',
      '',
      'Les listes sont paginées avec les paramètres :',
      '',
      '- `page` : Numéro de page (défaut: 1)',
      '- `limit` : Nombre d\'éléments par page (défaut: 20, max: 100)',
      '',
      '## Limites de taux',
      '',
      '- **Standard** : 1000 requêtes/heure',
      '- **Premium** : 5000 requêtes/heure',
      '- **Enterprise** : 10000 requêtes/heure',
      '',
      '🚀 **Prêt à commencer ?** Consultez le guide d\'authentification pour obtenir votre premier token !'
    ]
  },
  'authentification-api': {
    id: 'authentification-api',
    title: 'Authentification API',
    category: 'API et webhooks',
    description: 'Comment s\'authentifier et gérer les tokens d\'accès',
    readTime: '10 min',
    difficulty: 'Intermédiaire',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.8,
    views: 743,
    content: [
      '# Authentification API CassKai',
      '',
      'L\'API CassKai utilise des tokens JWT (JSON Web Tokens) pour l\'authentification.',
      '',
      '## Obtenir un token d\'API',
      '',
      '### 1. Via l\'interface CassKai',
      '',
      '1. Connectez-vous à votre compte CassKai',
      '2. Allez dans **Paramètres** → **Intégrations** → **Tokens API**',
      '3. Cliquez sur **Générer un nouveau token**',
      '4. Donnez un nom à votre token (ex: "Integration Shopify")',
      '5. Définissez les permissions nécessaires',
      '6. Copiez le token affiché (il ne sera plus visible après)',
      '',
      '### 2. Via l\'endpoint d\'authentification',
      '',
      '```http',
      'POST /v1/auth/login',
      'Content-Type: application/json',
      '',
      '{',
      '  "email": "votre-email@exemple.com",',
      '  "password": "votre-mot-de-passe"',
      '}',
      '```',
      '',
      '**Réponse :**',
      '```json',
      '{',
      '  "success": true,',
      '  "data": {',
      '    "access_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",',
      '    "refresh_token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...",',
      '    "expires_in": 3600,',
      '    "token_type": "Bearer"',
      '  }',
      '}',
      '```',
      '',
      '## Utiliser le token',
      '',
      '### Headers HTTP requis',
      '```http',
      'Authorization: Bearer YOUR_ACCESS_TOKEN',
      'Content-Type: application/json',
      'Accept: application/json',
      '```',
      '',
      '### Exemple avec cURL',
      '```bash',
      'curl -X GET \\',
      '  "https://api.casskai.app/v1/companies" \\',
      '  -H "Authorization: Bearer YOUR_ACCESS_TOKEN" \\',
      '  -H "Content-Type: application/json"',
      '```',
      '',
      '### Exemple avec JavaScript',
      '```javascript',
      'const response = await fetch("https://api.casskai.app/v1/companies", {',
      '  headers: {',
      '    "Authorization": "Bearer " + token,',
      '    "Content-Type": "application/json"',
      '  }',
      '});',
      '',
      'const data = await response.json();',
      '```',
      '',
      '## Gestion des tokens',
      '',
      '### Durée de vie',
      '- **Access token** : 1 heure',
      '- **Refresh token** : 30 jours',
      '- **API token (interface)** : Pas d\'expiration (révocable)',
      '',
      '### Renouveler un token',
      '```http',
      'POST /v1/auth/refresh',
      'Content-Type: application/json',
      '',
      '{',
      '  "refresh_token": "YOUR_REFRESH_TOKEN"',
      '}',
      '```',
      '',
      '### Révoquer un token',
      '```http',
      'POST /v1/auth/revoke',
      'Authorization: Bearer YOUR_ACCESS_TOKEN',
      'Content-Type: application/json',
      '',
      '{',
      '  "token": "TOKEN_TO_REVOKE"',
      '}',
      '```',
      '',
      '## Permissions et scopes',
      '',
      'Les tokens peuvent avoir différents niveaux d\'accès :',
      '',
      '- **read:companies** : Lire les informations d\'entreprise',
      '- **write:companies** : Modifier les informations d\'entreprise',
      '- **read:accounting** : Consulter les données comptables',
      '- **write:accounting** : Créer/modifier les écritures',
      '- **read:invoices** : Consulter les factures',
      '- **write:invoices** : Créer/modifier les factures',
      '',
      '## Erreurs d\'authentification',
      '',
      '### Token manquant (401)',
      '```json',
      '{',
      '  "success": false,',
      '  "error": {',
      '    "code": "MISSING_TOKEN",',
      '    "message": "Token d\'authentification requis"',
      '  }',
      '}',
      '```',
      '',
      '### Token invalide (401)',
      '```json',
      '{',
      '  "success": false,',
      '  "error": {',
      '    "code": "INVALID_TOKEN",',
      '    "message": "Token d\'authentification invalide"',
      '  }',
      '}',
      '```',
      '',
      '### Token expiré (401)',
      '```json',
      '{',
      '  "success": false,',
      '  "error": {',
      '    "code": "TOKEN_EXPIRED",',
      '    "message": "Token d\'authentification expiré"',
      '  }',
      '}',
      '```',
      '',
      '🔐 **Important** : Stockez vos tokens de manière sécurisée et ne les exposez jamais côté client !'
    ]
  },
  'endpoints-comptabilite': {
    id: 'endpoints-comptabilite',
    title: 'Endpoints de comptabilité',
    category: 'API et webhooks',
    description: 'API pour gérer les écritures comptables, journaux et comptes',
    readTime: '15 min',
    difficulty: 'Avancé',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.4,
    views: 412,
    content: [
      '# Endpoints de comptabilité',
      '',
      'Les endpoints de comptabilité permettent de gérer les écritures, journaux et plan comptable.',
      '',
      '## Plan comptable',
      '',
      '### Lister les comptes',
      '```http',
      'GET /v1/accounting/accounts',
      '```',
      '',
      '**Paramètres optionnels :**',
      '- `class` : Filtrer par classe de compte (1-8)',
      '- `active` : true/false pour les comptes actifs',
      '- `search` : Recherche par numéro ou libellé',
      '',
      '**Réponse :**',
      '```json',
      '{',
      '  "success": true,',
      '  "data": [',
      '    {',
      '      "id": "acc_123",',
      '      "number": "411000",',
      '      "name": "Clients",',
      '      "class": 4,',
      '      "type": "asset",',
      '      "active": true,',
      '      "created_at": "2025-01-15T10:00:00Z"',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '### Créer un compte',
      '```http',
      'POST /v1/accounting/accounts',
      'Content-Type: application/json',
      '',
      '{',
      '  "number": "512100",',
      '  "name": "Banque Crédit Agricole",',
      '  "class": 5,',
      '  "type": "asset",',
      '  "parent_account": "512000"',
      '}',
      '```',
      '',
      '## Journaux comptables',
      '',
      '### Lister les journaux',
      '```http',
      'GET /v1/accounting/journals',
      '```',
      '',
      '**Réponse :**',
      '```json',
      '{',
      '  "success": true,',
      '  "data": [',
      '    {',
      '      "id": "jnl_123",',
      '      "code": "VT",',
      '      "name": "Journal des ventes",',
      '      "type": "sale",',
      '      "active": true',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '### Types de journaux disponibles',
      '- **purchase** : Achats',
      '- **sale** : Ventes',
      '- **bank** : Banque',
      '- **cash** : Caisse',
      '- **general** : Opérations diverses',
      '',
      '## Écritures comptables',
      '',
      '### Lister les écritures',
      '```http',
      'GET /v1/accounting/entries',
      '```',
      '',
      '**Paramètres optionnels :**',
      '- `journal_id` : Filtrer par journal',
      '- `date_from` : Date de début (YYYY-MM-DD)',
      '- `date_to` : Date de fin (YYYY-MM-DD)',
      '- `account` : Filtrer par compte',
      '',
      '### Créer une écriture',
      '```http',
      'POST /v1/accounting/entries',
      'Content-Type: application/json',
      '',
      '{',
      '  "date": "2025-01-15",',
      '  "reference": "FAC001",',
      '  "journal_id": "jnl_123",',
      '  "description": "Facture client ABC",',
      '  "lines": [',
      '    {',
      '      "account_id": "acc_411",',
      '      "description": "Client ABC",',
      '      "debit": 1200.00,',
      '      "credit": 0',
      '    },',
      '    {',
      '      "account_id": "acc_701",',
      '      "description": "Vente produits",',
      '      "debit": 0,',
      '      "credit": 1000.00',
      '    },',
      '    {',
      '      "account_id": "acc_445",',
      '      "description": "TVA collectée",',
      '      "debit": 0,',
      '      "credit": 200.00',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '### Validation d\'écriture',
      'Les écritures doivent respecter :',
      '',
      '- **Équilibre** : Total débits = Total crédits',
      '- **Journal** : Journal existant et actif',
      '- **Comptes** : Comptes existants et compatibles',
      '- **Date** : Dans l\'exercice comptable ouvert',
      '',
      '### Modifier une écriture',
      '```http',
      'PUT /v1/accounting/entries/{entry_id}',
      '```',
      '',
      '⚠️ **Attention** : Seules les écritures non lettrées et dans l\'exercice ouvert peuvent être modifiées.',
      '',
      '## Balance et états comptables',
      '',
      '### Balance des comptes',
      '```http',
      'GET /v1/accounting/balance',
      '```',
      '',
      '**Paramètres :**',
      '- `date_from` : Date de début',
      '- `date_to` : Date de fin',
      '- `account_class` : Classe de comptes (1-8)',
      '',
      '### Grand livre',
      '```http',
      'GET /v1/accounting/ledger',
      '```',
      '',
      '### Bilan comptable',
      '```http',
      'GET /v1/accounting/balance-sheet',
      '```',
      '',
      '### Compte de résultat',
      '```http',
      'GET /v1/accounting/income-statement',
      '```',
      '',
      '## Clôture d\'exercice',
      '',
      '### Clôturer l\'exercice',
      '```http',
      'POST /v1/accounting/close-period',
      'Content-Type: application/json',
      '',
      '{',
      '  "closing_date": "2024-12-31",',
      '  "generate_reports": true',
      '}',
      '```',
      '',
      '📊 **Conseil** : Utilisez les webhooks pour être notifié des changements d\'état des écritures !'
    ]
  },
  'endpoints-facturation': {
    id: 'endpoints-facturation',
    title: 'Endpoints de facturation',
    category: 'API et webhooks',
    description: 'Créer, modifier et gérer les factures via l\'API',
    readTime: '12 min',
    difficulty: 'Avancé',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.7,
    views: 567,
    content: [
      '# Endpoints de facturation',
      '',
      'Les endpoints de facturation permettent de gérer factures, devis et avoirs.',
      '',
      '## Factures',
      '',
      '### Lister les factures',
      '```http',
      'GET /v1/invoices',
      '```',
      '',
      '**Paramètres optionnels :**',
      '- `status` : draft, sent, paid, overdue, cancelled',
      '- `customer_id` : Filtrer par client',
      '- `date_from` / `date_to` : Période',
      '- `number` : Numéro de facture',
      '',
      '**Réponse :**',
      '```json',
      '{',
      '  "success": true,',
      '  "data": [',
      '    {',
      '      "id": "inv_123",',
      '      "number": "FAC-2025-001",',
      '      "status": "sent",',
      '      "date": "2025-01-15",',
      '      "due_date": "2025-02-14",',
      '      "customer": {',
      '        "id": "cust_456",',
      '        "name": "Entreprise ABC",',
      '        "email": "comptabilite@abc.fr"',
      '      },',
      '      "total_ht": 1000.00,',
      '      "total_ttc": 1200.00,',
      '      "currency": "EUR"',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '### Créer une facture',
      '```http',
      'POST /v1/invoices',
      'Content-Type: application/json',
      '',
      '{',
      '  "customer_id": "cust_456",',
      '  "date": "2025-01-15",',
      '  "due_date": "2025-02-14",',
      '  "currency": "EUR",',
      '  "payment_terms": "30_days",',
      '  "lines": [',
      '    {',
      '      "description": "Développement site web",',
      '      "quantity": 1,',
      '      "unit_price": 1000.00,',
      '      "tax_rate": 20.0,',
      '      "account_code": "706000"',
      '    }',
      '  ],',
      '  "notes": "Merci pour votre confiance"',
      '}',
      '```',
      '',
      '### États de facture',
      '',
      '- **draft** : Brouillon (modifiable)',
      '- **sent** : Envoyée au client',
      '- **viewed** : Vue par le client',
      '- **paid** : Payée intégralement',
      '- **partial** : Payée partiellement',
      '- **overdue** : En retard de paiement',
      '- **cancelled** : Annulée',
      '',
      '### Envoyer une facture',
      '```http',
      'POST /v1/invoices/{invoice_id}/send',
      'Content-Type: application/json',
      '',
      '{',
      '  "email": "client@exemple.com",',
      '  "subject": "Facture FAC-2025-001",',
      '  "message": "Veuillez trouver ci-joint votre facture.",',
      '  "send_copy_to_me": true',
      '}',
      '```',
      '',
      '## Devis',
      '',
      '### Créer un devis',
      '```http',
      'POST /v1/quotes',
      'Content-Type: application/json',
      '',
      '{',
      '  "customer_id": "cust_456",',
      '  "date": "2025-01-15",',
      '  "validity_date": "2025-02-15",',
      '  "lines": [',
      '    {',
      '      "description": "Consultation SEO",',
      '      "quantity": 5,',
      '      "unit_price": 200.00,',
      '      "tax_rate": 20.0',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '### Convertir un devis en facture',
      '```http',
      'POST /v1/quotes/{quote_id}/convert',
      'Content-Type: application/json',
      '',
      '{',
      '  "invoice_date": "2025-01-15",',
      '  "due_date": "2025-02-14"',
      '}',
      '```',
      '',
      '## Avoirs',
      '',
      '### Créer un avoir',
      '```http',
      'POST /v1/credit-notes',
      'Content-Type: application/json',
      '',
      '{',
      '  "invoice_id": "inv_123",',
      '  "reason": "Retour produit défectueux",',
      '  "lines": [',
      '    {',
      '      "description": "Remboursement produit",',
      '      "quantity": 1,',
      '      "unit_price": -200.00,',
      '      "tax_rate": 20.0',
      '    }',
      '  ]',
      '}',
      '```',
      '',
      '## Paiements',
      '',
      '### Enregistrer un paiement',
      '```http',
      'POST /v1/invoices/{invoice_id}/payments',
      'Content-Type: application/json',
      '',
      '{',
      '  "amount": 1200.00,',
      '  "date": "2025-01-20",',
      '  "method": "bank_transfer",',
      '  "reference": "VIR123456",',
      '  "bank_account_id": "bank_789"',
      '}',
      '```',
      '',
      '### Méthodes de paiement',
      '- **bank_transfer** : Virement bancaire',
      '- **check** : Chèque',
      '- **cash** : Espèces',
      '- **credit_card** : Carte bancaire',
      '- **online** : Paiement en ligne',
      '',
      '## Clients',
      '',
      '### Créer un client',
      '```http',
      'POST /v1/customers',
      'Content-Type: application/json',
      '',
      '{',
      '  "company_name": "Entreprise ABC",',
      '  "contact_name": "Jean Dupont",',
      '  "email": "jean.dupont@abc.fr",',
      '  "phone": "+33 1 23 45 67 89",',
      '  "address": {',
      '    "street": "123 Rue de la Paix",',
      '    "city": "Paris",',
      '    "postal_code": "75001",',
      '    "country": "FR"',
      '  },',
      '  "vat_number": "FR12345678901",',
      '  "payment_terms": "30_days"',
      '}',
      '```',
      '',
      '## Numérotation automatique',
      '',
      'CassKai génère automatiquement les numéros :',
      '',
      '- **Factures** : FAC-YYYY-XXX',
      '- **Devis** : DEV-YYYY-XXX',
      '- **Avoirs** : AVO-YYYY-XXX',
      '',
      'Format personnalisable dans les paramètres de l\'entreprise.',
      '',
      '## Webhooks de facturation',
      '',
      'Événements disponibles :',
      '',
      '- `invoice.created` : Facture créée',
      '- `invoice.sent` : Facture envoyée',
      '- `invoice.paid` : Facture payée',
      '- `invoice.overdue` : Facture en retard',
      '',
      '💡 **Astuce** : Utilisez les webhooks pour automatiser votre suivi de paiements !'
    ]
  },
  'webhooks-configuration': {
    id: 'webhooks-configuration',
    title: 'Configuration des webhooks',
    category: 'API et webhooks',
    description: 'Recevoir des notifications en temps réel des événements CassKai',
    readTime: '20 min',
    difficulty: 'Avancé',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.2,
    views: 234,
    content: [
      '# Configuration des webhooks',
      '',
      'Les webhooks permettent de recevoir des notifications en temps réel lors d\'événements dans CassKai.',
      '',
      '## Qu\'est-ce qu\'un webhook ?',
      '',
      'Un webhook est une requête HTTP POST envoyée automatiquement à votre serveur quand un événement se produit dans CassKai.',
      '',
      '**Avantages :**',
      '- Notifications en temps réel',
      '- Pas de polling nécessaire',
      '- Intégration événementielle',
      '- Réduction de la charge serveur',
      '',
      '## Configuration',
      '',
      '### 1. Via l\'interface CassKai',
      '',
      '1. Allez dans **Paramètres** → **Intégrations** → **Webhooks**',
      '2. Cliquez sur **Nouveau webhook**',
      '3. Configurez l\'endpoint :',
      '   - **URL** : https://votre-serveur.com/webhook/casskai',
      '   - **Événements** : Sélectionnez les événements',
      '   - **Secret** : Clé secrète pour validation',
      '',
      '### 2. Via l\'API',
      '',
      '```http',
      'POST /v1/webhooks',
      'Content-Type: application/json',
      '',
      '{',
      '  "url": "https://votre-serveur.com/webhook/casskai",',
      '  "events": ["invoice.paid", "customer.created"],',
      '  "secret": "votre-secret-webhook",',
      '  "active": true',
      '}',
      '```',
      '',
      '## Événements disponibles',
      '',
      '### Facturation',
      '- `invoice.created` : Facture créée',
      '- `invoice.updated` : Facture modifiée',
      '- `invoice.sent` : Facture envoyée',
      '- `invoice.paid` : Facture payée',
      '- `invoice.overdue` : Facture en retard',
      '- `invoice.cancelled` : Facture annulée',
      '',
      '### Clients',
      '- `customer.created` : Client créé',
      '- `customer.updated` : Client modifié',
      '- `customer.deleted` : Client supprimé',
      '',
      '### Comptabilité',
      '- `entry.created` : Écriture créée',
      '- `entry.validated` : Écriture validée',
      '- `period.closed` : Période clôturée',
      '',
      '### Paiements',
      '- `payment.received` : Paiement reçu',
      '- `payment.failed` : Paiement échoué',
      '',
      '## Structure d\'un webhook',
      '',
      '### Headers HTTP',
      '```',
      'POST /webhook/casskai HTTP/1.1',
      'Host: votre-serveur.com',
      'Content-Type: application/json',
      'X-CassKai-Event: invoice.paid',
      'X-CassKai-Signature: sha256=abc123...',
      'X-CassKai-Delivery: 12345678-1234-1234-1234-123456789012',
      'User-Agent: CassKai-Webhook/1.0',
      '```',
      '',
      '### Payload JSON',
      '```json',
      '{',
      '  "id": "evt_123456789",',
      '  "event": "invoice.paid",',
      '  "created_at": "2025-01-15T14:30:00Z",',
      '  "data": {',
      '    "object": "invoice",',
      '    "id": "inv_123",',
      '    "number": "FAC-2025-001",',
      '    "status": "paid",',
      '    "total": 1200.00,',
      '    "customer": {',
      '      "id": "cust_456",',
      '      "name": "Entreprise ABC"',
      '    },',
      '    "payment": {',
      '      "amount": 1200.00,',
      '      "method": "bank_transfer",',
      '      "date": "2025-01-15"',
      '    }',
      '  }',
      '}',
      '```',
      '',
      '## Validation des webhooks',
      '',
      '### Vérification de signature',
      '',
      'CassKai signe chaque webhook avec HMAC-SHA256 :',
      '',
      '```javascript',
      'const crypto = require(\'crypto\');',
      '',
      'function validateWebhook(payload, signature, secret) {',
      '  const expectedSignature = crypto',
      '    .createHmac(\'sha256\', secret)',
      '    .update(payload, \'utf8\')',
      '    .digest(\'hex\');',
      '',
      '  return signature === `sha256=${expectedSignature}`;',
      '}',
      '```',
      '',
      '### Exemple Node.js/Express',
      '',
      '```javascript',
      'const express = require(\'express\');',
      'const crypto = require(\'crypto\');',
      '',
      'const app = express();',
      '',
      'app.use(\'/webhook\', express.raw({ type: \'application/json\' }));',
      '',
      'app.post(\'/webhook/casskai\', (req, res) => {',
      '  const signature = req.headers[\'x-casskai-signature\'];',
      '  const event = req.headers[\'x-casskai-event\'];',
      '  const payload = req.body;',
      '',
      '  // Validation de signature',
      '  if (!validateWebhook(payload, signature, process.env.WEBHOOK_SECRET)) {',
      '    return res.status(401).send(\'Signature invalide\');',
      '  }',
      '',
      '  // Traitement de l\'événement',
      '  switch (event) {',
      '    case \'invoice.paid\':',
      '      handleInvoicePaid(JSON.parse(payload));',
      '      break;',
      '    case \'customer.created\':',
      '      handleCustomerCreated(JSON.parse(payload));',
      '      break;',
      '  }',
      '',
      '  res.status(200).send(\'OK\');',
      '});',
      '```',
      '',
      '## Gestion des échecs',
      '',
      '### Stratégie de retry',
      '',
      'En cas d\'échec (code HTTP non 2xx) :',
      '',
      '1. **Retry immédiat** après 1 seconde',
      '2. **Retry exponential** : 2s, 4s, 8s, 16s, 32s',
      '3. **Abandon** après 5 tentatives',
      '',
      '### Codes de réponse attendus',
      '',
      '- **200-299** : Succès (pas de retry)',
      '- **400-499** : Erreur client (pas de retry)',
      '- **500-599** : Erreur serveur (retry)',
      '- **Timeout** : Délai dépassé (retry)',
      '',
      '### Désactivation automatique',
      '',
      'Un webhook est automatiquement désactivé si :',
      '',
      '- Plus de 20 échecs consécutifs',
      '- Aucune réponse 2xx depuis 7 jours',
      '- URL inaccessible depuis 48h',
      '',
      '## Test et debugging',
      '',
      '### Tester un webhook',
      '',
      '```http',
      'POST /v1/webhooks/{webhook_id}/test',
      'Content-Type: application/json',
      '',
      '{',
      '  "event": "invoice.paid"',
      '}',
      '```',
      '',
      '### Logs de webhooks',
      '',
      'Consultez les logs dans l\'interface :',
      '**Paramètres** → **Intégrations** → **Webhooks** → **Logs**',
      '',
      '### Outil de debug : Webhook.site',
      '',
      'Pour tester rapidement :',
      '1. Allez sur https://webhook.site',
      '2. Copiez l\'URL générée',
      '3. Configurez cette URL comme webhook',
      '4. Déclenchez un événement',
      '5. Observez la requête reçue',
      '',
      '## Bonnes pratiques',
      '',
      '### Sécurité',
      '- ✅ Toujours valider la signature',
      '- ✅ Utiliser HTTPS uniquement',
      '- ✅ Filtrer les événements nécessaires',
      '- ✅ Implémenter une whitelist IP',
      '',
      '### Performance',
      '- ✅ Répondre rapidement (< 10s)',
      '- ✅ Traitement asynchrone des tâches lourdes',
      '- ✅ Queue pour les traitements longs',
      '- ✅ Idempotence des traitements',
      '',
      '### Monitoring',
      '- ✅ Logger tous les webhooks reçus',
      '- ✅ Alertes sur les échecs',
      '- ✅ Métriques de performance',
      '- ✅ Health check de l\'endpoint',
      '',
      '🔔 **Important** : Testez toujours vos webhooks avant la mise en production !'
    ]
  },
  'exemples-integration': {
    id: 'exemples-integration',
    title: 'Exemples d\'intégration',
    category: 'API et webhooks',
    description: 'Cas pratiques d\'intégration avec des outils populaires',
    readTime: '25 min',
    difficulty: 'Avancé',
    lastUpdated: '2025-01-15',
    author: 'Équipe technique CassKai',
    rating: 4.3,
    views: 189,
    content: [
      '# Exemples d\'intégration',
      '',
      'Découvrez des cas pratiques d\'intégration de CassKai avec des outils populaires.',
      '',
      '## 1. Intégration Shopify → CassKai',
      '',
      'Synchroniser automatiquement les commandes Shopify vers CassKai.',
      '',
      '### Webhook Shopify',
      '',
      '```javascript',
      '// server.js - Réception webhook Shopify',
      'app.post(\'/webhook/shopify/order\', (req, res) => {',
      '  const order = req.body;',
      '',
      '  // Créer le client s\'il n\'existe pas',
      '  const customer = await createCustomerIfNotExists({',
      '    email: order.customer.email,',
      '    name: `${order.customer.first_name} ${order.customer.last_name}`,',
      '    address: order.billing_address',
      '  });',
      '',
      '  // Créer la facture',
      '  const invoice = await casskai.invoices.create({',
      '    customer_id: customer.id,',
      '    external_reference: order.order_number,',
      '    date: order.created_at,',
      '    lines: order.line_items.map(item => ({',
      '      description: item.name,',
      '      quantity: item.quantity,',
      '      unit_price: parseFloat(item.price),',
      '      tax_rate: calculateTaxRate(item.tax_lines)',
      '    }))',
      '  });',
      '',
      '  res.status(200).send(\'OK\');',
      '});',
      '```',
      '',
      '### Client CassKai',
      '',
      '```javascript',
      '// casskai-client.js',
      'class CassKaiClient {',
      '  constructor(apiToken) {',
      '    this.apiToken = apiToken;',
      '    this.baseUrl = \'https://api.casskai.app/v1\';',
      '  }',
      '',
      '  async request(method, endpoint, data = null) {',
      '    const response = await fetch(`${this.baseUrl}${endpoint}`, {',
      '      method,',
      '      headers: {',
      '        \'Authorization\': `Bearer ${this.apiToken}`,',
      '        \'Content-Type\': \'application/json\'',
      '      },',
      '      body: data ? JSON.stringify(data) : null',
      '    });',
      '',
      '    return response.json();',
      '  }',
      '',
      '  // Wrapper methods',
      '  invoices = {',
      '    create: (data) => this.request(\'POST\', \'/invoices\', data),',
      '    get: (id) => this.request(\'GET\', `/invoices/${id}`),',
      '    list: (params) => this.request(\'GET\', \'/invoices\' + querystring(params))',
      '  };',
      '',
      '  customers = {',
      '    create: (data) => this.request(\'POST\', \'/customers\', data),',
      '    findByEmail: (email) => this.request(\'GET\', `/customers?email=${email}`)',
      '  };',
      '}',
      '```',
      '',
      '## 2. Intégration WooCommerce → CassKai',
      '',
      '### Plugin WordPress',
      '',
      '```php',
      '<?php',
      '// casskai-woocommerce.php',
      '',
      'add_action(\'woocommerce_order_status_completed\', \'casskai_create_invoice\');',
      '',
      'function casskai_create_invoice($order_id) {',
      '    $order = wc_get_order($order_id);',
      '    ',
      '    $invoice_data = array(',
      '        \'customer_id\' => casskai_get_or_create_customer($order),',
      '        \'date\' => date(\'Y-m-d\'),',
      '        \'external_reference\' => $order->get_order_number(),',
      '        \'lines\' => array()',
      '    );',
      '    ',
      '    // Ajouter les lignes de commande',
      '    foreach ($order->get_items() as $item) {',
      '        $invoice_data[\'lines\'][] = array(',
      '            \'description\' => $item->get_name(),',
      '            \'quantity\' => $item->get_quantity(),',
      '            \'unit_price\' => $item->get_total() / $item->get_quantity(),',
      '            \'tax_rate\' => casskai_calculate_tax_rate($item)',
      '        );',
      '    }',
      '    ',
      '    casskai_api_request(\'POST\', \'/invoices\', $invoice_data);',
      '}',
      '',
      'function casskai_api_request($method, $endpoint, $data = null) {',
      '    $api_token = get_option(\'casskai_api_token\');',
      '    ',
      '    $args = array(',
      '        \'method\' => $method,',
      '        \'headers\' => array(',
      '            \'Authorization\' => \'Bearer \' . $api_token,',
      '            \'Content-Type\' => \'application/json\'',
      '        )',
      '    );',
      '    ',
      '    if ($data) {',
      '        $args[\'body\'] = json_encode($data);',
      '    }',
      '    ',
      '    return wp_remote_request(\'https://api.casskai.app/v1\' . $endpoint, $args);',
      '}',
      '?>',
      '```',
      '',
      '## 3. Synchronisation Stripe → CassKai',
      '',
      '### Webhook Stripe pour paiements',
      '',
      '```javascript',
      '// stripe-webhook.js',
      'const stripe = require(\'stripe\')(process.env.STRIPE_SECRET_KEY);',
      '',
      'app.post(\'/webhook/stripe\', express.raw({type: \'application/json\'}), async (req, res) => {',
      '  const sig = req.headers[\'stripe-signature\'];',
      '  let event;',
      '',
      '  try {',
      '    event = stripe.webhooks.constructEvent(req.body, sig, process.env.STRIPE_ENDPOINT_SECRET);',
      '  } catch (err) {',
      '    return res.status(400).send(`Webhook Error: ${err.message}`);',
      '  }',
      '',
      '  switch (event.type) {',
      '    case \'payment_intent.succeeded\':',
      '      await handlePaymentSuccess(event.data.object);',
      '      break;',
      '    case \'invoice.payment_succeeded\':',
      '      await handleInvoicePayment(event.data.object);',
      '      break;',
      '  }',
      '',
      '  res.json({received: true});',
      '});',
      '',
      'async function handlePaymentSuccess(paymentIntent) {',
      '  const invoiceNumber = paymentIntent.metadata.invoice_number;',
      '  ',
      '  // Récupérer la facture CassKai',
      '  const invoices = await casskai.invoices.list({',
      '    number: invoiceNumber',
      '  });',
      '  ',
      '  if (invoices.data.length > 0) {',
      '    // Enregistrer le paiement',
      '    await casskai.invoices.payments.create(invoices.data[0].id, {',
      '      amount: paymentIntent.amount / 100, // Stripe en centimes',
      '      method: \'credit_card\',',
      '      reference: paymentIntent.id,',
      '      date: new Date().toISOString().split(\'T\')[0]',
      '    });',
      '  }',
      '}',
      '```',
      '',
      '## 4. Intégration CRM → CassKai',
      '',
      '### Synchronisation clients HubSpot',
      '',
      '```python',
      '# hubspot_sync.py',
      'import requests',
      'from hubspot import HubSpot',
      'from datetime import datetime',
      '',
      'class HubSpotCassKaiSync:',
      '    def __init__(self, hubspot_token, casskai_token):',
      '        self.hubspot = HubSpot(access_token=hubspot_token)',
      '        self.casskai_token = casskai_token',
      '        self.casskai_base_url = \'https://api.casskai.app/v1\'',
      '    ',
      '    def sync_customers(self):',
      '        # Récupérer les contacts HubSpot',
      '        contacts = self.hubspot.crm.contacts.get_all()',
      '        ',
      '        for contact in contacts:',
      '            self.create_or_update_customer(contact)',
      '    ',
      '    def create_or_update_customer(self, hubspot_contact):',
      '        customer_data = {',
      '            \'company_name\': hubspot_contact.properties.get(\'company\'),',
      '            \'contact_name\': f"{hubspot_contact.properties.get(\'firstname\')} {hubspot_contact.properties.get(\'lastname\')}",',
      '            \'email\': hubspot_contact.properties.get(\'email\'),',
      '            \'phone\': hubspot_contact.properties.get(\'phone\'),',
      '            \'external_id\': str(hubspot_contact.id)',
      '        }',
      '        ',
      '        # Vérifier si le client existe déjà',
      '        existing = self.casskai_request(\'GET\', f\'/customers?external_id={hubspot_contact.id}\')',
      '        ',
      '        if existing[\'data\']:',
      '            # Mettre à jour',
      '            customer_id = existing[\'data\'][0][\'id\']',
      '            self.casskai_request(\'PUT\', f\'/customers/{customer_id}\', customer_data)',
      '        else:',
      '            # Créer',
      '            self.casskai_request(\'POST\', \'/customers\', customer_data)',
      '    ',
      '    def casskai_request(self, method, endpoint, data=None):',
      '        headers = {',
      '            \'Authorization\': f\'Bearer {self.casskai_token}\',',
      '            \'Content-Type\': \'application/json\'',
      '        }',
      '        ',
      '        response = requests.request(',
      '            method,',
      '            f\'{self.casskai_base_url}{endpoint}\',',
      '            headers=headers,',
      '            json=data',
      '        )',
      '        ',
      '        return response.json()',
      '',
      '# Utilisation',
      'sync = HubSpotCassKaiSync(',
      '    hubspot_token=\'your-hubspot-token\',',
      '    casskai_token=\'your-casskai-token\'',
      ')',
      'sync.sync_customers()',
      '```',
      '',
      '## 5. Export vers Excel/Google Sheets',
      '',
      '### Export automatique vers Google Sheets',
      '',
      '```javascript',
      '// google-sheets-export.js',
      'const { GoogleSpreadsheet } = require(\'google-spreadsheet\');',
      'const { JWT } = require(\'google-auth-library\');',
      '',
      'class CassKaiSheetsExporter {',
      '  constructor(cassKaiToken, sheetsCredentials, sheetId) {',
      '    this.cassKaiToken = cassKaiToken;',
      '    this.serviceAccountAuth = new JWT({',
      '      email: sheetsCredentials.client_email,',
      '      key: sheetsCredentials.private_key,',
      '      scopes: [\'https://www.googleapis.com/auth/spreadsheets\']',
      '    });',
      '    this.sheetId = sheetId;',
      '  }',
      '',
      '  async exportInvoices(startDate, endDate) {',
      '    // Récupérer les factures',
      '    const response = await fetch(`https://api.casskai.app/v1/invoices?date_from=${startDate}&date_to=${endDate}`, {',
      '      headers: {',
      '        \'Authorization\': `Bearer ${this.cassKaiToken}`',
      '      }',
      '    });',
      '    const invoices = await response.json();',
      '',
      '    // Ouvrir le Google Sheet',
      '    const doc = new GoogleSpreadsheet(this.sheetId, this.serviceAccountAuth);',
      '    await doc.loadInfo();',
      '    const sheet = doc.sheetsByIndex[0];',
      '',
      '    // Effacer le contenu existant',
      '    await sheet.clear();',
      '',
      '    // Ajouter les en-têtes',
      '    await sheet.setHeaderRow([',
      '      \'Numéro\', \'Date\', \'Client\', \'Montant HT\', \'TVA\', \'Montant TTC\', \'Statut\'',
      '    ]);',
      '',
      '    // Ajouter les données',
      '    const rows = invoices.data.map(invoice => ({',
      '      \'Numéro\': invoice.number,',
      '      \'Date\': invoice.date,',
      '      \'Client\': invoice.customer.name,',
      '      \'Montant HT\': invoice.total_ht,',
      '      \'TVA\': invoice.total_ttc - invoice.total_ht,',
      '      \'Montant TTC\': invoice.total_ttc,',
      '      \'Statut\': invoice.status',
      '    }));',
      '',
      '    await sheet.addRows(rows);',
      '    logger.info(`${rows.length} factures exportées vers Google Sheets`);',
      '  }',
      '}',
      '',
      '// Planification avec cron',
      'const cron = require(\'node-cron\');',
      '',
      'cron.schedule(\'0 9 1 * *\', () => {',
      '  // Export mensuel le 1er à 9h',
      '  const lastMonth = new Date();',
      '  lastMonth.setMonth(lastMonth.getMonth() - 1);',
      '  ',
      '  const startDate = new Date(lastMonth.getFullYear(), lastMonth.getMonth(), 1)',
      '    .toISOString().split(\'T\')[0];',
      '  const endDate = new Date(lastMonth.getFullYear(), lastMonth.getMonth() + 1, 0)',
      '    .toISOString().split(\'T\')[0];',
      '  ',
      '  exporter.exportInvoices(startDate, endDate);',
      '});',
      '```',
      '',
      '## 6. Application mobile React Native',
      '',
      '### Client mobile simple',
      '',
      '```jsx',
      '// CassKaiApp.js',
      'import React, { useState, useEffect } from \'react\';',
      'import { View, FlatList, Text, StyleSheet } from \'react-native\';',
      '',
      'const CassKaiApp = () => {',
      '  const [invoices, setInvoices] = useState([]);',
      '  const [loading, setLoading] = useState(true);',
      '',
      '  useEffect(() => {',
      '    fetchInvoices();',
      '  }, []);',
      '',
      '  const fetchInvoices = async () => {',
      '    try {',
      '      const response = await fetch(\'https://api.casskai.app/v1/invoices\', {',
      '        headers: {',
      '          \'Authorization\': \'Bearer YOUR_TOKEN\'',
      '        }',
      '      });',
      '      const data = await response.json();',
      '      setInvoices(data.data);',
      '    } catch (error) {',
      '      logger.error(\'Erreur fetch:\', error);',
      '    } finally {',
      '      setLoading(false);',
      '    }',
      '  };',
      '',
      '  const renderInvoice = ({ item }) => (',
      '    <View style={styles.invoiceItem}>',
      '      <Text style={styles.invoiceNumber}>{item.number}</Text>',
      '      <Text>{item.customer.name}</Text>',
      '      <Text style={styles.amount}>{item.total_ttc}€</Text>',
      '      <Text style={[styles.status, styles[item.status]]}>{item.status}</Text>',
      '    </View>',
      '  );',
      '',
      '  return (',
      '    <View style={styles.container}>',
      '      <FlatList',
      '        data={invoices}',
      '        renderItem={renderInvoice}',
      '        keyExtractor={(item) => item.id}',
      '        refreshing={loading}',
      '        onRefresh={fetchInvoices}',
      '      />',
      '    </View>',
      '  );',
      '};',
      '```',
      '',
      '## Conseils d\'intégration',
      '',
      '### Gestion d\'erreurs',
      '',
      '```javascript',
      'async function robustApiCall(endpoint, data, retries = 3) {',
      '  for (let i = 0; i < retries; i++) {',
      '    try {',
      '      const response = await casskai.request(\'POST\', endpoint, data);',
      '      return response;',
      '    } catch (error) {',
      '      if (error.status === 429) {',
      '        // Rate limit - attendre avant retry',
      '        await sleep(Math.pow(2, i) * 1000);',
      '        continue;',
      '      }',
      '      if (error.status >= 500) {',
      '        // Erreur serveur - retry',
      '        await sleep(1000);',
      '        continue;',
      '      }',
      '      // Erreur client - pas de retry',
      '      throw error;',
      '    }',
      '  }',
      '  throw new Error(\'Max retries exceeded\');',
      '}',
      '```',
      '',
      '### Cache et performance',
      '',
      '```javascript',
      'const NodeCache = require(\'node-cache\');',
      'const cache = new NodeCache({ stdTTL: 300 }); // 5 minutes',
      '',
      'async function getCachedCustomer(email) {',
      '  const cacheKey = `customer:${email}`;',
      '  let customer = cache.get(cacheKey);',
      '  ',
      '  if (!customer) {',
      '    const response = await casskai.customers.findByEmail(email);',
      '    customer = response.data[0];',
      '    cache.set(cacheKey, customer);',
      '  }',
      '  ',
      '  return customer;',
      '}',
      '```',
      '',
      '🛠️ **Prochaines étapes** : Adaptez ces exemples à votre architecture et testez sur un environnement de développement !'
    ]
  }
};

const DocumentationArticlePage = () => {
  const { category: categoryParam, article: articleId } = useParams();
  const navigate = useNavigate();
  const { t } = useTranslation();
  const { toast } = useToast();
  const [hasRated, setHasRated] = useState(false);
  const [userRating, setUserRating] = useState<'positive' | 'negative' | null>(null);

  // Gestionnaires d'événements
  const handleRating = (rating: 'positive' | 'negative') => {
    setHasRated(true);
    setUserRating(rating);
    
    (toast as any)({
      title: "Merci pour votre retour !",
      description: rating === 'positive'
        ? "Nous sommes ravis que cet article vous ait été utile."
        : "Nous prendrons en compte votre retour pour améliorer cet article.",
      duration: 3000
    });
  };

  const handleShare = async () => {
    if (navigator.share) {
      try {
        await navigator.share({
          title: article?.title || 'Article CassKai',
          text: article?.description || '',
          url: window.location.href
        });
      } catch (error) {
        logger.info('Partage annulé')
      }
    } else {
      toast({
        title: "Partage",
        description: "Fonctionnalité de partage non disponible sur votre navigateur"
      });
    }
  };

  const handleCopyLink = async () => {
    try {
      await navigator.clipboard.writeText(window.location.href);
      toast({
        title: "Lien copié !",
        description: "Le lien de l'article a été copié dans le presse-papiers"
      });
    } catch (error) {
      toast({
        variant: "destructive",
        title: "Erreur",
        description: "Impossible de copier le lien"
      });
    }
  };

  // handleLiveChat supprimé - remplacé par WhatsAppChat

  const handleContactSupport = () => {
    window.open(`mailto:support@casskai.app?subject=${  encodeURIComponent(`Question sur: ${  article?.title || 'Documentation'}`)}`);
    toast({
      title: "Contact support",
      description: "Votre client email va s'ouvrir"
    });
  };

  // Récupérer l'article depuis la base de données ou les catégories
  const getArticle = () => {
    // D'abord essayer dans articlesDatabase
    if (articlesDatabase[articleId]) {
      return articlesDatabase[articleId];
    }

    // Si pas trouvé, chercher dans les catégories
    if (categoryParam && categoriesData[categoryParam]) {
      const categoryArticles = categoriesData[categoryParam].articles;
      const foundArticle = categoryArticles.find(article => article.id === articleId);

      if (foundArticle) {
        // Convertir l'article de catégorie au format attendu par le rendu
        return {
          id: foundArticle.id,
          title: foundArticle.title,
          category: categoriesData[categoryParam].title,
          description: foundArticle.description,
          readTime: foundArticle.readTime,
          difficulty: foundArticle.difficulty,
          lastUpdated: '2025-01-15', // Date par défaut
          author: 'Équipe CassKai',
          rating: 4.5,
          views: foundArticle.views,
          content: [`# ${foundArticle.title}`, '', foundArticle.description, '', '## Contenu en cours de développement', '', 'Cette section sera bientôt complétée avec des informations détaillées.']
        };
      }
    }

    return null;
  };

  const article = getArticle();

  // Si l'article n'existe pas, afficher une page 404
  if (!article) {
    return (
      <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800">
        <PublicNavigation variant="legal" />
        <div className="pt-24 pb-16">
          <div className="flex items-center justify-center h-64">
            <div className="text-center">
              <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
                Article non trouvé
              </h1>
              <p className="text-gray-600 dark:text-gray-300 mb-8">
                L'article demandé n'existe pas ou a été déplacé.
              </p>
              <Button onClick={() => navigate('/help')}>
                <ArrowLeft className="w-4 h-4 mr-2" />
                Retour au centre d'aide
              </Button>
            </div>
          </div>
        </div>
      </div>
    );
  }

  const renderContent = (contentLines) => {
    return contentLines.map((line, index) => {
      if (line.startsWith('# ')) {
        return <h1 key={index} className="text-3xl font-bold text-gray-900 dark:text-white mb-6 mt-8">{line.substring(2)}</h1>;
      }
      if (line.startsWith('## ')) {
        return <h2 key={index} className="text-2xl font-bold text-gray-900 dark:text-white mb-4 mt-8">{line.substring(3)}</h2>;
      }
      if (line.startsWith('### ')) {
        return <h3 key={index} className="text-xl font-semibold text-gray-900 dark:text-white mb-3 mt-6">{line.substring(4)}</h3>;
      }
      if (line.startsWith('#### ')) {
        return <h4 key={index} className="text-lg font-semibold text-gray-900 dark:text-white mb-2 mt-4">{line.substring(5)}</h4>;
      }
      if (line.startsWith('- ') || line.startsWith('* ')) {
        return <li key={index} className="text-gray-700 dark:text-gray-300 mb-1 ml-4">{line.substring(2)}</li>;
      }
      if (line.trim() === '') {
        return <br key={index} />;
      }
      if (line.startsWith('**') && line.endsWith('**')) {
        return <p key={index} className="font-semibold text-gray-900 dark:text-white mb-2">{line.slice(2, -2)}</p>;
      }
      return <p key={index} className="text-gray-700 dark:text-gray-300 mb-3 leading-relaxed">{line}</p>;
    });
  };

  return (
    <div className="min-h-screen bg-gradient-to-br from-gray-50 to-white dark:from-gray-900 dark:to-gray-800">
      <PublicNavigation variant="legal" />
      <div className="pt-24 pb-16">
      {/* Header */}
      <div className="bg-white dark:bg-gray-800 border-b border-gray-200 dark:border-gray-700">
        <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="flex items-center mb-6">
            <Button
              variant="ghost"
              onClick={() => navigate('/help')}
              className="mr-4"
            >
              <ArrowLeft className="w-4 h-4 mr-2" />
              Centre d'aide
            </Button>
            <Badge variant="outline">{article.category}</Badge>
          </div>
          
          <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-4">
            {article.title}
          </h1>
          
          <p className="text-xl text-gray-600 dark:text-gray-300 mb-6">
            {article.description}
          </p>
          
          <div className="flex items-center space-x-6 text-sm text-gray-500 dark:text-gray-400">
            <div className="flex items-center">
              <Clock className="w-4 h-4 mr-2" />
              {article.readTime}
            </div>
            <div className="flex items-center">
              <User className="w-4 h-4 mr-2" />
              {article.author}
            </div>
            <div className="flex items-center">
              <Calendar className="w-4 h-4 mr-2" />
              {article.lastUpdated}
            </div>
            <div className="flex items-center">
              <Star className="w-4 h-4 mr-2 text-yellow-500" />
              {article.rating}/5
            </div>
          </div>
        </div>
      </div>

      {/* Contenu */}
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8 py-12">
        <div className="grid grid-cols-1 lg:grid-cols-4 gap-8">
          {/* Contenu principal */}
          <div className="lg:col-span-3">
            <Card>
              <CardContent className="p-8">
                <div className="prose prose-lg dark:prose-invert max-w-none">
                  {renderContent(article.content)}
                </div>
              </CardContent>
            </Card>
            
            {/* Actions */}
            <div className="mt-8 flex items-center justify-between">
              <div className="flex items-center space-x-4">
                <span className="text-sm text-gray-600 dark:text-gray-300">
                  Cet article vous a-t-il été utile ?
                </span>
                <Button 
                  variant={userRating === 'positive' ? 'default' : 'outline'} 
                  size="sm"
                  onClick={() => handleRating('positive')}
                  disabled={hasRated}
                >
                  <ThumbsUp className="w-4 h-4 mr-2" />
                  Oui
                </Button>
                <Button 
                  variant={userRating === 'negative' ? 'default' : 'outline'} 
                  size="sm"
                  onClick={() => handleRating('negative')}
                  disabled={hasRated}
                >
                  <ThumbsDown className="w-4 h-4 mr-2" />
                  Non
                </Button>
              </div>
              
              <div className="flex items-center space-x-2">
                <Button variant="outline" size="sm" onClick={handleShare}>
                  <Share2 className="w-4 h-4 mr-2" />
                  Partager
                </Button>
                <Button variant="outline" size="sm" onClick={handleCopyLink}>
                  <Copy className="w-4 h-4 mr-2" />
                  Copier le lien
                </Button>
              </div>
            </div>
          </div>
          
          {/* Sidebar */}
          <div className="lg:col-span-1">
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center">
                  <BookOpen className="w-5 h-5 mr-2" />
                  Articles liés
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {article.relatedArticles?.map((relatedId, index) => (
                    <Button
                      key={index}
                      variant="ghost"
                      className="w-full justify-start text-left h-auto p-3"
                      onClick={() => navigate(`/docs/${relatedId}`)}
                    >
                      <ArrowRight className="w-4 h-4 mr-2 flex-shrink-0" />
                      <span className="text-sm">{relatedId.replace(/-/g, ' ')}</span>
                    </Button>
                  ))}
                </div>
              </CardContent>
            </Card>
            
            <Card className="mt-6">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <MessageCircle className="w-5 h-5 mr-2" />
                  Besoin d'aide ?
                </CardTitle>
              </CardHeader>
              <CardContent>
                <p className="text-sm text-gray-600 dark:text-gray-300 mb-4">
                  Vous ne trouvez pas la réponse à votre question ?
                </p>
                <WhatsAppChat
                  messageType="documentation"
                  message={`Bonjour ! J'ai une question sur l'article "${article?.title}" de votre documentation CassKai.`}
                  className="w-full mb-3"
                />
                <Button variant="outline" className="w-full" onClick={handleContactSupport}>
                  Contacter le support
                </Button>
              </CardContent>
            </Card>
          </div>
        </div>
      </div>
      </div>
    </div>
  );
};

export default DocumentationArticlePage;