name: Deploy to Hostinger

on:
  workflow_run:
    workflows: ['CI/CD Pipeline']   # Nom EXACT du workflow CI
    types: [completed]
  workflow_dispatch:

concurrency:
  group: deploy-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Download dist artifact
      uses: actions/download-artifact@v4
      with:
        name: dist
        path: dist
        github-token: ${{ secrets.GITHUB_TOKEN }}
        repository: ${{ github.repository }}
        run-id: ${{ github.event.workflow_run.id }}

    - name: Verify build output
      run: |
        echo "📦 Vérification du contenu du build téléchargé..."
        ls -la dist/
        ls -la dist/assets/ || echo "Pas de dossier assets"

    - name: Create .htaccess for React Router
      run: |
        cat > dist/.htaccess << 'EOF'
        <IfModule mod_rewrite.c>
            RewriteEngine On
            
            # Security headers
            <IfModule mod_headers.c>
                Header always set X-Content-Type-Options nosniff
                Header always set X-Frame-Options DENY
                Header always set X-XSS-Protection "1; mode=block"
                Header always set Referrer-Policy "strict-origin-when-cross-origin"
                Header always set Permissions-Policy "camera=(), microphone=(), geolocation=()"
            </IfModule>
            
            # Cache static assets
            <IfModule mod_expires.c>
                ExpiresActive On
                ExpiresByType text/css "access plus 1 year"
                ExpiresByType application/javascript "access plus 1 year"
                ExpiresByType image/png "access plus 1 year"
                ExpiresByType image/jpg "access plus 1 year"
                ExpiresByType image/jpeg "access plus 1 year"
                ExpiresByType image/gif "access plus 1 year"
                ExpiresByType image/svg+xml "access plus 1 year"
                ExpiresByType font/woff2 "access plus 1 year"
            </IfModule>
            
            # Block access to sensitive files
            <Files ".env*">
                Order deny,allow
                Deny from all
            </Files>
            
            <Files "config*">
                Order deny,allow
                Deny from all
            </Files>
            
            # React Router - redirect all requests to index.html
            RewriteRule ^index\.html$ - [L]
            RewriteCond %{REQUEST_FILENAME} !-f
            RewriteCond %{REQUEST_FILENAME} !-d
            RewriteRule . /index.html [L]
        </IfModule>
        EOF

    - name: Deploy to Hostinger via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: 82.25.113.130
        username: u657259520.casskai.app
        password: ${{ secrets.HOSTINGER_FTP_PASSWORD }}
        local-dir: ./dist/
        server-dir: /public_html/
        port: 21
        protocol: ftp
        exclude: |
          **/.git*
          **/.git*/**
          **/node_modules/**
          **/.env*